### ISSUE TITLE
pip install mapapi failed

### ISSUE THREAD

**Issue by JavaProgrammerLB** [yimian/mapapi#1]
I type the command 'pip install mapapi 'into cmd with my windows 7
I got an error:
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-5fhpdy0s\mapapi

 UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 40: illegal multibyte sequence.

**Comment by starplanet** [comment]
I use the command 'pip install mapapi' on my windows 10 machine, all goes well.

What's your system language code? is it 'zh_CN.utf8' or other?

Umm，I update mappai to 0.1.2, you can try again.

**Comment by JavaProgrammerLB** [comment]
@starplanet 
Today ’pip install mapapi' runs success
